/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlannTool;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import jxl.Cell;
import jxl.Sheet;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/**
 *
 * @author gabor_hanacsek
 */
public class Anyagelados extends javax.swing.JFrame {

    /**
     * Creates new form Mastermodule
     */
    //ebbe a tömbbe fogjuk tárolni az adatokat
    public static List<String[]> eladaslista = new ArrayList<>();
    public static Workbook workbook = null;
    public static JFileChooser fileChooser = new JFileChooser();

    public Anyagelados() throws SQLException, ClassNotFoundException {
        initComponents();
        seticon();
//amikor megnyilik az ablak lequeryzzuk az adatokat es eltesszuk egy tombbe

        String query = "select * from M_anyageladas";

        planconnect pc = new planconnect();
        pc.planconnect(query);

        while (pc.rs.next()) {
            String[] lista = new String[10];
            lista[0] = pc.rs.getString(1);
            lista[1] = pc.rs.getString(2);
            lista[2] = pc.rs.getString(3);
            lista[3] = pc.rs.getString(4);
            lista[4] = pc.rs.getString(5);
            lista[5] = pc.rs.getString(6);
            lista[6] = pc.rs.getString(7);
            lista[7] = pc.rs.getString(8);
            lista[8] = pc.rs.getString(9);
            lista[9] = pc.rs.getString(10);

            eladaslista.add(lista);

        }

        pc.kinyir();

        Anyagelados.jTable3.setCellSelectionEnabled(true);

        Anyagelados.jTable3.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                //I want something to happen before the row change is triggered on the UI.  
                Anyaglistakibontas a = new Anyaglistakibontas();
                //ha pn oszlopban vagyunk ráadásul
                if (Anyagelados.jTable3.getSelectedColumn() == 3) {

                    a.tablabair();

                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anyag eladás");

        jButton1.setText("Igény beolvasása");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Új adatok feltöltése");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PN", "QTY", "Mikor", "Komment", "Summ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setMinWidth(150);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Other Organization", "QTY", "item prefix nélkül", "PartNumber", "Item material status 2", "LT", "Buyer name", "Comment"
            }
        ));
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable3KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        fileChooser.setCurrentDirectory(new File("C:\\Users\\gabor_hanacsek\\Desktop\\anyag eladás"));
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            // Creating a Workbook from an Excel file (.xls or .xlsx)
            try {

                workbook = WorkbookFactory.create(new File(fileChooser.getSelectedFile().toString()));
                jTextField1.setText(fileChooser.getSelectedFile().getName());
            } catch (EncryptedDocumentException ex) {
                Logger.getLogger(Anyagelados.class.getName()).log(Level.SEVERE, null, ex);
                infobox info = new infobox();
                info.infoBox(ex.getMessage(), "Hiba!");
            } catch (IOException ex) {
                Logger.getLogger(Anyagelados.class.getName()).log(Level.SEVERE, null, ex);
                infobox info = new infobox();
                info.infoBox(ex.getMessage(), "Hiba!");
            }

            //kiszedjuk a tablamodellt
            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) Anyagelados.jTable3.getModel();
            model.setRowCount(0);
            // Retrieving the number of sheets in the Workbook

            org.apache.poi.ss.usermodel.Sheet sheet = workbook.getSheetAt(0);
            // Create a DataFormatter to format and get each cell's value as String
            DataFormatter dataFormatter = new DataFormatter();
            Iterator<Row> rowIterator = sheet.rowIterator();
            while (rowIterator.hasNext()) {
                Row row = rowIterator.next();
                //ha van kovetkezo sor hozzaadunk egyet a modellhez is

                model.addRow(new Object[]{});
                // Now let's iterate over the columns of the current row
                Iterator<org.apache.poi.ss.usermodel.Cell> cellIterator = row.cellIterator();

                while (cellIterator.hasNext()) {
                    org.apache.poi.ss.usermodel.Cell cell = cellIterator.next();
                    String cellValue = dataFormatter.formatCellValue((org.apache.poi.ss.usermodel.Cell) cell);
                    //hozzaadjuk a cellahoz a cellvalue erteket , ha nem sikerül hozzáadunk egy uj oszlopot
                    try {
                        model.setValueAt(cellValue, row.getRowNum(), cell.getColumnIndex());
                    } catch (Exception e) {

                        model.addColumn("");
                        model.setValueAt(cellValue, row.getRowNum(), cell.getColumnIndex());

                    }

                }

            }

            try {
                workbook.close();
            } catch (IOException ex) {
                Logger.getLogger(Anyagelados.class.getName()).log(Level.SEVERE, null, ex);
            }

            Anyagelados.jTable3.setModel(model);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void seticon() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kepek/anyagos2.png")));

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // feltöltjük az adatbázisba az új adatokat

        String Query = "insert ignore M_anyageladas (OO,QTY,IPN,PartNumber,IStatus,LT,Buyername,Komment) values ";

        //bejarjuk a jtablet es osszeszedjuk az adatokat , ahol nem nulla az oo és a pn
        String feltoltadat = "";

        for (int i = 0; i < jTable3.getRowCount(); i++) {

            if (jTable3.getValueAt(i, 0) != null && !jTable3.getValueAt(i, 3).toString().equals("") && jTable3.getValueAt(i, 3) != null) {

                String a = "'" + jTable3.getValueAt(i, 0).toString() + "'";
                String b = "'" + jTable3.getValueAt(i, 1).toString() + "'";
                String c = "'" + jTable3.getValueAt(i, 2).toString() + "'";
                String d = "'" + jTable3.getValueAt(i, 3).toString() + "'";
                String e = "'" + jTable3.getValueAt(i, 4).toString() + "'";
                String f = "'" + jTable3.getValueAt(i, 5).toString() + "'";
                String g = "'" + jTable3.getValueAt(i, 6).toString() + "'";
                String h = "''";
                try {
                    h = "'" + jTable3.getValueAt(i, 7).toString() + "'";
                } catch (Exception ex) {

                }

                feltoltadat += "(" + a + "," + b + "," + c + "," + d + "," + e + "," + f + "," + g + "," + h + "),";

            }

        }

        feltoltadat = feltoltadat.substring(0, feltoltadat.length() - 1);

        Query += feltoltadat;

        //feltoltjuk
        planconnect pc = new planconnect();

        pc.feltolt(Query, true);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyReleased
        // TODO add your handling code here:
        Anyaglistakibontas a = new Anyaglistakibontas();
        try {
            a.celleditor();
        } catch (IOException ex) {
            Logger.getLogger(Anyagelados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anyagelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anyagelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anyagelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anyagelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Mastermodule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
