/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlannTool;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;

/**
 *
 * @author gabor_hanacsek
 */
public class cellavalaszto extends javax.swing.JFrame {

    Betervezo bt;
    public static String neve;

    public cellavalaszto(Betervezo b) throws SQLException, ClassNotFoundException {
        initComponents();
        bt = b;
        //lekerdezzuk az adatbazisbol a cellakat
        planconnect pc = new planconnect();
        String query = "SELECT * FROM planningdb.tc_becells;";
        ResultSet rs = (ResultSet) pc.planconnect(query);
        DefaultListModel lm1 = new DefaultListModel();
        DefaultListModel lm2 = new DefaultListModel();
        lm1.removeAllElements();
        lm2.removeAllElements();
        jList1.setModel(lm1);
        jList2.setModel(lm2);
        jComboBox1.requestFocus();

        while (rs.next()) {

            lm1.addElement(rs.getString(2));

        }

        jList1.setModel(lm1);

        // lekerdezzuk a felhasznalokat es betesszuk a comboboxba
        query = "select * from tc_users";
        pc.planconnect(query);

        while (pc.rs.next()) {

            jComboBox1.addItem(pc.rs.getString(2));

        }

        jComboBox1.setSelectedIndex(-1);

//        Besheet sheet = new Besheet();
//        bt.jTabbedPane1.add("valami", sheet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cella választó");

        jScrollPane1.setViewportView(jList1);

        jList2.setToolTipText("");
        jScrollPane2.setViewportView(jList2);

        jButton1.setText("-->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<--");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Lekér");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jLabel1.setText("Felhasználó:");

        jButton4.setText("Mentés");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Lekér");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel lm2 = new DefaultListModel();
        for (int i = 0; i < jList1.getModel().getSize(); i++) {

            if (jList1.isSelectedIndex(i)) {

                lm2.addElement(jList1.getModel().getElementAt(i));

            }

        }

        jList2.setModel(lm2);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultListModel lm2 = new DefaultListModel();
        lm2 = (DefaultListModel) jList2.getModel();

        if (this.jList2.getSelectedIndices().length > 0) {
            int[] selectedIndices = jList2.getSelectedIndices();
            for (int i = selectedIndices.length - 1; i >= 0; i--) {
                lm2.removeElementAt(selectedIndices[i]);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String querybe = "";
        DefaultListModel lm2 = new DefaultListModel();
        lm2 = (DefaultListModel) jList2.getModel();
        //osszerakjuk hogy milyen allomasok vannak a jlistben
        for (int i = 0; i < lm2.size(); i++) {

            querybe += "'" + lm2.getElementAt(i) + "',";

        }
        querybe = querybe.substring(0, querybe.length() - 1);
        //lekerdezzuk az idjukat
        String query = "select tc_becells.idtc_cells from tc_becells where tc_becells.cellname in (" + querybe + ")";

        planconnect pc = new planconnect();
        try {
            pc.planconnect(query);
            //felhasznalato formava alakitjuk az update queryhez
            querybe = "";
            while (pc.rs.next()) {

                querybe += pc.rs.getString(1) + ",";

            }

            querybe = querybe.substring(0, querybe.length() - 1);

            //updatelunk
            query = "update tc_users set tc_users.cellaids = '" + querybe + "' where tc_users.username = '" + jComboBox1.getSelectedItem().toString() + "'";
            try {
                pc.feltolt(query, true);
                infobox inf = new infobox();
                inf.infoBox("Sikeres mentés!", "Mentés");
            } catch (Exception e) {
                infobox inf = new infobox();
                inf.infoBox("Sikertelen mentés!", "Mentés");
            }
        } catch (SQLException ex) {
            Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (jComboBox1.getSelectedIndex() != -1) {
            String query = "select tc_users.cellaids from tc_users where tc_users.username = '" + jComboBox1.getSelectedItem().toString() + "'";
            //System.out.println(query);

            String cellak = "";
            planconnect pc = new planconnect();
            try {
                pc.planconnect(query);

                while (pc.rs.next()) {

                    cellak = pc.rs.getString(1);
                    //System.out.println(cellak);

                }

            } catch (SQLException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            }

            //feldaraboljuk az rs eredmenyet
            String[] cellaktomb = cellak.split(",");

            //atalakitjuk hasznalhato formava a queryhez
            String querybe = "";

            for (int i = 0; i < cellaktomb.length; i++) {

                querybe += "'" + cellaktomb[i].toString() + "',";

            }
            querybe = querybe.substring(0, querybe.length() - 1);

            //osszeqallitjuk a queryt
            query = "SELECT tc_becells.cellname from tc_becells where tc_becells.idtc_cells in (" + querybe + ")";
            DefaultListModel lm2 = new DefaultListModel();

            try {
                //lekerdezzuk

                pc.planconnect(query);
                while (pc.rs.next()) {
                    lm2.addElement(pc.rs.getString(1));
                }

                jList2.setModel(lm2);

            } catch (SQLException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        jButton3.requestFocus();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        //lekérjük a sheeteket
        Betervezo.Besheets.clear();
        for (int i = 0; i < jList2.getModel().getSize(); i++) {

            Besheet sheet = null;
            try {
                sheet = new Besheet(bt);
            } catch (SQLException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            }
            bt.jTabbedPane1.addTab(jList2.getModel().getElementAt(i), sheet);
            neve = jList2.getModel().getElementAt(i);
            Betervezo.Besheets.put(jList2.getModel().getElementAt(i), sheet);
            try {
                sheet.parts();
                sheet.workstations();
            } catch (SQLException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        bt.jButton1.setFocusable(false);
        bt.jButton3.requestFocus();
        
        this.setVisible(false);
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed

        jButton5.requestFocus();

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (jComboBox1.getSelectedIndex() != -1) {
                String query = "select tc_users.cellaids from tc_users where tc_users.username = '" + jComboBox1.getSelectedItem().toString() + "'";
                //System.out.println(query);

                String cellak = "";
                planconnect pc = new planconnect();
                try {
                    pc.planconnect(query);

                    while (pc.rs.next()) {

                        cellak = pc.rs.getString(1);
                        //System.out.println(cellak);

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                }

                //feldaraboljuk az rs eredmenyet
                String[] cellaktomb = cellak.split(",");

                //atalakitjuk hasznalhato formava a queryhez
                String querybe = "";

                for (int i = 0; i < cellaktomb.length; i++) {

                    querybe += "'" + cellaktomb[i].toString() + "',";

                }
                querybe = querybe.substring(0, querybe.length() - 1);

                //osszeqallitjuk a queryt
                query = "SELECT tc_becells.cellname from tc_becells where tc_becells.idtc_cells in (" + querybe + ")";
                DefaultListModel lm2 = new DefaultListModel();

                try {
                    //lekerdezzuk

                    pc.planconnect(query);
                    while (pc.rs.next()) {
                        lm2.addElement(pc.rs.getString(1));
                    }

                    jList2.setModel(lm2);

                } catch (SQLException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            jButton3.requestFocus();

        }


    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        
         // TODO add your handling code here:

        //lekérjük a sheeteket
        Betervezo.Besheets.clear();
        for (int i = 0; i < jList2.getModel().getSize(); i++) {

            Besheet sheet = null;
            try {
                sheet = new Besheet(bt);
            } catch (SQLException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            }
            bt.jTabbedPane1.addTab(jList2.getModel().getElementAt(i), sheet);
            neve = jList2.getModel().getElementAt(i);
            Betervezo.Besheets.put(jList2.getModel().getElementAt(i), sheet);
            try {
                sheet.parts();
                sheet.workstations();
            } catch (SQLException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        bt.jButton1.setFocusable(false);
        bt.jButton3.requestFocus();
        
        this.setVisible(false);
        
     
    }//GEN-LAST:event_jButton3KeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        
        jButton5.requestFocus();

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (jComboBox1.getSelectedIndex() != -1) {
                String query = "select tc_users.cellaids from tc_users where tc_users.username = '" + jComboBox1.getSelectedItem().toString() + "'";
                //System.out.println(query);

                String cellak = "";
                planconnect pc = new planconnect();
                try {
                    pc.planconnect(query);

                    while (pc.rs.next()) {

                        cellak = pc.rs.getString(1);
                        //System.out.println(cellak);

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                }

                //feldaraboljuk az rs eredmenyet
                String[] cellaktomb = cellak.split(",");

                //atalakitjuk hasznalhato formava a queryhez
                String querybe = "";

                for (int i = 0; i < cellaktomb.length; i++) {

                    querybe += "'" + cellaktomb[i].toString() + "',";

                }
                querybe = querybe.substring(0, querybe.length() - 1);

                //osszeqallitjuk a queryt
                query = "SELECT tc_becells.cellname from tc_becells where tc_becells.idtc_cells in (" + querybe + ")";
                DefaultListModel lm2 = new DefaultListModel();

                try {
                    //lekerdezzuk

                    pc.planconnect(query);
                    while (pc.rs.next()) {
                        lm2.addElement(pc.rs.getString(1));
                    }

                    jList2.setModel(lm2);

                } catch (SQLException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(cellavalaszto.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            jButton3.requestFocus();

        }

    }//GEN-LAST:event_jButton5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cellavalaszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cellavalaszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cellavalaszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cellavalaszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new cellavalaszto().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
