/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlannTool;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author gabor_hanacsek
 */
public class Tc_Besetup extends javax.swing.JFrame {

    /**
     * Creates new form tc_besetup
     */
    public List<String> defaultadat1 = new ArrayList<String>();
    public List<String> defaultadat2 = new ArrayList<String>();
    public List<String> defaultadat3 = new ArrayList<String>();

    public Tc_Besetup() throws SQLException, ClassNotFoundException {

        initComponents();

        //tabla tesszuk a meglevo setup beallitasokat
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        String query = "select  tc_prodmatrix.idtc_prodmatrix , tc_bepns.partnumber , tc_becells.cellname , tc_bestations.workstation , tc_prodmatrix.ciklusido ,tc_bepns.smt_pn from tc_prodmatrix left join tc_bepns on tc_prodmatrix.id_tc_bepns = tc_bepns.idtc_bepns  left join tc_becells on tc_becells.idtc_cells = tc_prodmatrix.id_tc_becells left join tc_bestations on tc_bestations.idtc_bestations = tc_prodmatrix.id_tc_bestations";
        planconnect pc;
        pc = new planconnect();

        ResultSet rs = (ResultSet) pc.planconnect(query);

        while (rs.next()) {

            model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDouble(5), rs.getString(6)});

        }

        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.setDefaultRenderer(Object.class, centerRenderer);
        jTable1.setModel(model);

        //pn feltoltese a jlistbe
        query = "SELECT * FROM planningdb.tc_bepns";
        rs = (ResultSet) pc.planconnect(query);
        DefaultListModel lm2 = new DefaultListModel();

        while (rs.next()) {

            lm2.addElement(rs.getString(2));
            defaultadat1.add(rs.getString(2));

        }

        jList2.setModel(lm2);

        //cella feltoltese
        query = "SELECT * FROM planningdb.tc_becells;";
        rs = (ResultSet) pc.planconnect(query);
        DefaultListModel lm1 = new DefaultListModel();

        while (rs.next()) {

            lm1.addElement(rs.getString(2));
            defaultadat2.add(rs.getString(2));

        }

        jList1.setModel(lm1);

        //workstation feltoltese
        query = "SELECT * FROM planningdb.tc_bestations;";
        rs = (ResultSet) pc.planconnect(query);
        DefaultListModel lm3 = new DefaultListModel();

        while (rs.next()) {

            lm3.addElement(rs.getString(2));
            defaultadat3.add(rs.getString(2));

        }

        pc.kinyir();
        jList4.setModel(lm3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField9 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setup!");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PartNumber", "Cella", "Workstation", "DB/Óra", "SMT-PN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jButton1.setText("Pn mentése");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Partnumber felvétele");

        jLabel6.setText("Cella felvétele");

        jButton2.setText("Cella mentése");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("WorkStation felvétele");

        jButton3.setText("WorkS mentése");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList2);

        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(jList4);

        jLabel1.setText("DB/Óra");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Keresés a táblázatban!");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jLabel3.setText("Keresés");

        jLabel4.setText("Keresés");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });

        jLabel8.setText("Keresés");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });

        jButton4.setText("Ment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Partnumber");

        jLabel10.setText("Cella");

        jLabel11.setText("WorkStation");

        jToggleButton1.setText("Töröl");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlannTool/kepek/kapocs1.png"))); // NOI18N
        jButton5.setToolTipText("Az SMT és a TOP L partnumber összekapcsolása!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("SMT-PN");

        jLabel13.setText("SMT-TOP L");

        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("<html>A variantos SMT termékeknél használj % -ot! PL: LFHB2926695%</html>");

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setText("Töröl");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel9)
                                .addGap(52, 52, 52))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(115, 115, 115)
                                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(38, 38, 38))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel11)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(133, 133, 133)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jButton4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        jTabbedPane1.addTab("Pn és Cella beállítások", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Műszakjelentés cím"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jButton6.setText("Ment");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cellaválasztó címlista (universal name)", "Cellaids", "Slides"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(1);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jButton7.setText("Ment");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("+ sor");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("+ sor");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton10))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addComponent(jButton10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("E-mail és hozzáférés beállítások", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        planconnect pc = new planconnect();
        String query = "Insert ignore tc_bepns (partnumber) values ('" + jTextField1.getText().trim() + "');";
        try {
            pc.feltolt(query, true);

        } catch (Exception e) {
            infobox info = new infobox();
            info.infoBox("A feltöltés sikertelen!!", "Mentés infó!");
        }

        //frissitjuk a pnjlistet
        ResultSet rs = null;

        query = "SELECT * FROM planningdb.tc_bepns";
        try {
            rs = (ResultSet) pc.planconnect(query);
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel lm2 = new DefaultListModel();
        lm2.removeAllElements();
        try {
            while (rs.next()) {

                lm2.addElement(rs.getString(2));
                defaultadat1.add(rs.getString(2));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        jList2.setModel(lm2);

        //frissitjuk a partnumber  adatokat a sheeteken
        for (int n = 0; n < Tc_Betervezo.Tervezotabbed.getTabCount(); n++) {

            query = "select tc_bepns.partnumber from tc_bepns \n"
                    + "left join tc_prodmatrix on tc_prodmatrix.id_tc_bepns = tc_bepns.idtc_bepns\n"
                    + "left join tc_becells on tc_prodmatrix.id_tc_becells = tc_becells.idtc_cells\n"
                    + "where tc_becells.cellname = '" + Tc_Betervezo.Tervezotabbed.getTitleAt(n) + "'";

            //kiszedjuk a regieket
            Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(n)).partnumbers.clear();

            try {
                pc.planconnect(query);
            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                while (pc.rs.next()) {

                    Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(n)).partnumbers.add(pc.rs.getString(1));

                }
            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

            pc.kinyir();

        }
//letezik e a pn ellenorzeshez
        try {
            Tc_Betervezo.pncheck();
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        planconnect pc = new planconnect();
        String query = "Insert ignore tc_becells (cellname) values ('" + jTextField5.getText().trim() + "');";
        try {
            pc.feltolt(query, true);

        } catch (Exception e) {
            infobox info = new infobox();
            info.infoBox("A feltöltés sikertelen!!", "Mentés infó!");
        }

        //frissitjuk a cellalistat
        query = "SELECT * FROM planningdb.tc_becells;";
        ResultSet rs = null;
        try {
            rs = (ResultSet) pc.planconnect(query);
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel lm1 = new DefaultListModel();

        try {
            while (rs.next()) {

                lm1.addElement(rs.getString(2));
                defaultadat2.add(rs.getString(2));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        jList1.setModel(lm1);
        pc.kinyir();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        planconnect pc = new planconnect();
        String query = "Insert ignore tc_bestations (workstation) values ('" + jTextField6.getText().trim() + "');";
        try {
            pc.feltolt(query, true);

        } catch (Exception e) {
            infobox info = new infobox();
            info.infoBox("A feltöltés sikertelen!!", "Mentés infó!");
        }

        //frissitjuk a station listet
        query = "SELECT * FROM planningdb.tc_bestations;";
        ResultSet rs = null;
        try {
            rs = (ResultSet) pc.planconnect(query);
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel lm3 = new DefaultListModel();

        try {
            while (rs.next()) {

                lm3.addElement(rs.getString(2));
                defaultadat3.add(rs.getString(2));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        jList4.setModel(lm3);

        try {
            Tc_Betervezo.wscheck();
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        pc.kinyir();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:

        String query = jTextField3.getText().trim();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        tablesorter tr = new tablesorter();
        tr.filter(query, model, jTable1);

    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed

        String filter = jTextField4.getText();
        jlistfilterfromtestbox fili = new jlistfilterfromtestbox();
        jList2.setModel(fili.filterModel((DefaultListModel<String>) jList2.getModel(), filter, (ArrayList<String>) defaultadat1));


    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        String filter = jTextField7.getText();
        jlistfilterfromtestbox fili = new jlistfilterfromtestbox();
        jList1.setModel(fili.filterModel((DefaultListModel<String>) jList1.getModel(), filter, (ArrayList<String>) defaultadat2));
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
        String filter = jTextField8.getText();
        jlistfilterfromtestbox fili = new jlistfilterfromtestbox();
        jList4.setModel(fili.filterModel((DefaultListModel<String>) jList4.getModel(), filter, (ArrayList<String>) defaultadat3));

    }//GEN-LAST:event_jTextField8KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //lekérdezzük a pn id-t
        planconnect pc = new planconnect();
        String pnid = "";
        String cellid = "";
        String wsid = "";
        String query = "select tc_bepns.idtc_bepns from tc_bepns where tc_bepns.partnumber = '" + jList2.getSelectedValue() + "'";
        try {
            pc.planconnect(query);
            while (pc.rs.next()) {
                pnid = pc.rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        //lekérdezzük a cella id-t
        query = "select tc_becells.idtc_cells from tc_becells where tc_becells.cellname ='" + jList1.getSelectedValue() + "'";
        try {
            pc.planconnect(query);
            while (pc.rs.next()) {
                cellid = pc.rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        //lekerdezzuk a ws id-t
        query = "select tc_bestations.idtc_bestations from tc_bestations where tc_bestations.workstation = '" + jList4.getSelectedValue() + "'";
        try {
            pc.planconnect(query);
            while (pc.rs.next()) {
                wsid = pc.rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        //lekerdezzuk , hogy van e ismetlodes
        query = "SELECT tc_prodmatrix.idtc_prodmatrix as id from tc_prodmatrix where (tc_prodmatrix.id_tc_bepns = '" + pnid + "' and tc_prodmatrix.id_tc_becells = '" + cellid + "' and tc_prodmatrix.id_tc_bestations = '" + wsid + "')";
        try {
            if (jTextField2.getText().equals("") || jList2.isSelectionEmpty() || jList1.isSelectionEmpty() || jList4.isSelectionEmpty()) {

                infobox inf = new infobox();
                inf.infoBox("Nem adtál meg valamilyen szükséges adatot!", "Hiba!");

            }
            pc.planconnect(query);
            //ha van mar adat frissitjuk
            if (pc.rs.next()) {

                query = "update tc_prodmatrix set tc_prodmatrix.ciklusido = " + Double.parseDouble(jTextField2.getText()) + " where (tc_prodmatrix.id_tc_bepns = '" + pnid + "' and tc_prodmatrix.id_tc_becells = '" + cellid + "' and tc_prodmatrix.id_tc_bestations = '" + wsid + "')";
                pc.feltolt(query, true);
                infobox inf = new infobox();
                inf.infoBox("Az adatot frissítettük!", "Frissítés történt!");

            } //ha nincs meg bent az adat beirjuk
            else {

                query = "insert into tc_prodmatrix (tc_prodmatrix.id_tc_bepns,tc_prodmatrix.id_tc_becells,tc_prodmatrix.id_tc_bestations,tc_prodmatrix.ciklusido) values (" + pnid + "," + cellid + "," + wsid + "," + Double.parseDouble(jTextField2.getText()) + ")";
                pc.feltolt(query, true);
                infobox inf = new infobox();
                inf.infoBox("Az adatot rögzítettük", "Új adat érkezett!");

            }

        } catch (SQLException ex) {

            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        //frissitjuk a tablat
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        query = "select tc_prodmatrix.idtc_prodmatrix , tc_bepns.partnumber , tc_becells.cellname , tc_bestations.workstation , tc_prodmatrix.ciklusido , tc_bepns.smt_pn from tc_prodmatrix left join tc_bepns on tc_prodmatrix.id_tc_bepns = tc_bepns.idtc_bepns  left join tc_becells on tc_becells.idtc_cells = tc_prodmatrix.id_tc_becells left join tc_bestations on tc_bestations.idtc_bestations = tc_prodmatrix.id_tc_bestations";

        pc = new planconnect();

        ResultSet rs = null;
        try {
            rs = (ResultSet) pc.planconnect(query);
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while (rs.next()) {

                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDouble(5), rs.getString(6)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.setDefaultRenderer(Object.class, centerRenderer);
        jTable1.setModel(model);

        //frissitjuk a sheet adatait , hogy frissuljon a kalkulátor
        //kinullazzuk a ciklusidok adatokat
        Tc_Betervezo.ciklusidok.clear();

        //lekerdezzuk a ciklusidoket
        query = "select tc_becells.cellname , tc_bepns.partnumber , tc_bestations.workstation , tc_prodmatrix.ciklusido from tc_prodmatrix \n"
                + "left join tc_becells on tc_becells.idtc_cells = tc_prodmatrix.id_tc_becells \n"
                + "left join tc_bepns on tc_bepns.idtc_bepns = tc_prodmatrix.id_tc_bepns\n"
                + "left join tc_bestations on tc_bestations.idtc_bestations = tc_prodmatrix.id_tc_bestations";
        pc = new planconnect();
        try {
            pc.planconnect(query);
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            pc.rs.last();
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }
        int utsosor = 0;
        try {
            utsosor = pc.rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pc.rs.beforeFirst();
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        String[][] ciklusidok = new String[utsosor][4];
        int i = 0;
        try {
            while (pc.rs.next()) {

                ciklusidok[i][0] = pc.rs.getString(1);
                ciklusidok[i][1] = pc.rs.getString(2);
                ciklusidok[i][2] = pc.rs.getString(3);
                ciklusidok[i][3] = pc.rs.getString(4);

                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        Tc_Betervezo.ciklusidok.add(ciklusidok);

        //frissitjuk a workstation adatokat
        for (int n = 0; n < Tc_Betervezo.Tervezotabbed.getTabCount(); n++) {

            //kiszedjuk a regieket
            Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(n)).workstations.clear();

            query = "SELECT tc_bestations.workstation  from tc_bestations where tc_bestations.idtc_bestations in \n"
                    + "(select distinct tc_prodmatrix.id_tc_bestations from tc_prodmatrix where tc_prodmatrix.id_tc_becells  = \n"
                    + "(SELECT tc_becells.idtc_cells FROM planningdb.tc_becells where tc_becells.cellname = '" + Tc_Betervezo.Tervezotabbed.getTitleAt(n) + "'))";

            try {
                pc.planconnect(query);
            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                while (pc.rs.next()) {

                    Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(n)).workstations.add(pc.rs.getString(1));

                }
            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        //frissitjuk a partnumber  adatokat a sheeteken
        for (int n = 0; n < Tc_Betervezo.Tervezotabbed.getTabCount(); n++) {

            query = "select tc_bepns.partnumber from tc_bepns \n"
                    + "left join tc_prodmatrix on tc_prodmatrix.id_tc_bepns = tc_bepns.idtc_bepns\n"
                    + "left join tc_becells on tc_prodmatrix.id_tc_becells = tc_becells.idtc_cells\n"
                    + "where tc_becells.cellname = '" + Tc_Betervezo.Tervezotabbed.getTitleAt(n) + "'";

            //kiszedjuk a regieket
            Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(n)).partnumbers.clear();

            try {
                pc.planconnect(query);
            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                while (pc.rs.next()) {

                    Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(n)).partnumbers.add(pc.rs.getString(1));

                }
            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        pc.kinyir();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int[] selectedrows = jTable1.getSelectedRows();

        String querybe = "";

        for (int i = 0; i < selectedrows.length; i++) {

            querybe += "'" + jTable1.getValueAt(selectedrows[i], 0).toString() + "',";
        }

        querybe = querybe.substring(0, querybe.length() - 1);
        String query = "DELETE from tc_prodmatrix where tc_prodmatrix.idtc_prodmatrix in (" + querybe + ")";
        planconnect pc = new planconnect();
        try {
            pc.feltolt(query, true);
            infobox info = new infobox();
            info.infoBox("Az adatokat sikeresen töröltük!", "Törlés történt!");

        } catch (Exception e) {

            infobox inf = new infobox();
            inf.infoBox("A törlés nem valósult meg!", "Hiba a törlés során!");

        }

        //frissítjük a táblát!
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        query = "select tc_prodmatrix.idtc_prodmatrix , tc_bepns.partnumber , tc_becells.cellname , tc_bestations.workstation , tc_prodmatrix.ciklusido from tc_prodmatrix left join tc_bepns on tc_prodmatrix.id_tc_bepns = tc_bepns.idtc_bepns  left join tc_becells on tc_becells.idtc_cells = tc_prodmatrix.id_tc_becells left join tc_bestations on tc_bestations.idtc_bestations = tc_prodmatrix.id_tc_bestations";

        pc = new planconnect();

        ResultSet rs = null;
        try {
            rs = (ResultSet) pc.planconnect(query);
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while (rs.next()) {

                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDouble(5)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
        }

        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.setDefaultRenderer(Object.class, centerRenderer);
        jTable1.setModel(model);


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (jTextField9.getText().length() > 0 && jList2.getSelectedValue() != null) {

            planconnect pc = new planconnect();
            String query = "update tc_bepns set tc_bepns.smt_pn  = '" + jTextField9.getText() + "' where tc_bepns.partnumber = '" + jList2.getSelectedValue().toString() + "'";
            pc.feltolt(query, true);

        } else {

            infobox info = new infobox();
            info.infoBox("Nem adtad meg a szükséges adatokat! (SMT és TOP L PN)!", "Hiba!");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:

        if (jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex()).equals("E-mail és hozzáférés beállítások")) {
            //lekerdezzuk a cimlistat
            DefaultTableModel model = new DefaultTableModel();
            DefaultTableModel model3 = new DefaultTableModel();
            model3 = (DefaultTableModel) jTable3.getModel();
            model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            model3.setRowCount(0);
            String query = "SELECT Muszakjelentes.Cím FROM planningdb.Muszakjelentes order by Cím";
            planconnect pc = new planconnect();

            try {
                pc.planconnect(query);
                //betesszuk tablaba
                while (pc.rs.next()) {

                    model.addRow(new Object[]{pc.rs.getString(1)});

                }

            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

            model.addRow(new Object[]{null});
            //feltoltjuk a cellavalaszto tablat
            query = "SELECT tc_users.username , tc_users.cellaids , tc_users.slides  FROM planningdb.tc_users";

            try {
                pc.planconnect(query);
                //betesszuk tablaba
                while (pc.rs.next()) {

                    model3.addRow(new Object[]{pc.rs.getString(1), pc.rs.getString(2), pc.rs.getString(3)});

                }

            } catch (SQLException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
            }

            model3.addRow(new Object[]{null, null, null});

        }


    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //mentjük a címlistát

        //String query = "insert into muszakjelentes (cim) values ";
        String queryvalues = "";

        for (int i = 0; i < jTable2.getRowCount(); i++) {

            try {
                if (!jTable2.getValueAt(i, 0).toString().equals("") && jTable2.getValueAt(i, 0) != null) {
                    queryvalues += "('" + jTable2.getValueAt(i, 0).toString() + "'),";
                }
            } catch (Exception e) {
            }

        }

        queryvalues = queryvalues.substring(0, queryvalues.length() - 2);
        String query = "insert into Muszakjelentes (cím) values" + queryvalues + ")";
        String truncate = "truncate Muszakjelentes";
        planconnect pc = new planconnect();
        pc.feltolt(truncate, false);
        pc.feltolt(query, true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //mentjük a cellavalszto adatokat

        //String query = "insert into muszakjelentes (cim) values ";
        String queryvalues = "";

        for (int i = 0; i < jTable3.getRowCount(); i++) {
            String cellak = "";
            String szin = "";
            try {
                cellak = jTable3.getValueAt(i, 1).toString();
            } catch (Exception e) {

                cellak = "null";

            }

            try {
                szin = jTable3.getValueAt(i, 2).toString();
            } catch (Exception e) {
                szin = "007,027,050,009,147,192";

            }

            try {
                if (!jTable3.getValueAt(i, 0).toString().equals("") && jTable3.getValueAt(i, 0) != null) {
                    queryvalues += "('" + jTable3.getValueAt(i, 0).toString() + "','" + cellak + "','" + szin + "'),";
                }
            } catch (Exception e) {
            }

        }

        queryvalues = queryvalues.substring(0, queryvalues.length() - 2);
        String query = "insert into tc_users (username , cellaids , slides) values" + queryvalues + ")";

        String truncate = "truncate tc_users";

        planconnect pc = new planconnect();
        pc.feltolt(truncate, false);
        pc.feltolt(query, true);


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // létrehozunk egy inputdialogot

        String input = JOptionPane.showInputDialog("A törlés megerősítése , írd be , DELETE!");
//ha stimmel a szoveg
        try {
            if (input.equals("DELETE!")) {

//összeszedjük , hogy miket kell törölni
                String pn = "";
                String ws = "";
                String cell = "";
                String cellid = "";
                String wsid = "";
                String pnid = "";
                try {
                    pn = jList2.getSelectedValue().toString();
                } catch (Exception e) {
                }

                try {
                    ws = jList4.getSelectedValue().toString();
                } catch (Exception e) {
                }
                try {
                    cell = jList1.getSelectedValue().toString();
                } catch (Exception e) {
                }

                planconnect pc = new planconnect();

//töröljük azokat a tételeket a prodmatrixbol amik ezzel kapcsolatba hozhatóak , ehhez kell az id-jük
//cella
                if (cell.length() > 0) {

                    String query = "select * from tc_becells where tc_becells.cellname = '" + cell + "'";
                    try {
                        pc.planconnect(query);
                        while (pc.rs.next()) {

                            cellid = pc.rs.getString(1);
//kitoroljuk a prodmatrixbol az ehez kapcsolodo teteleket
                            query = "delete from tc_prodmatrix where tc_prodmatrix.id_tc_becells = '" + cellid + "'";
                            pc.feltolt(query, false);
//kitoroljuk a tablabol is
                            query = "delete from tc_becells where tc_becells.cellname = '" + cell + "';";
                            pc.feltolt(query, false);

                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

//ws
                if (ws.length() > 0) {

                    String query = "SELECT * FROM planningdb.tc_bestations where tc_bestations.workstation = '" + ws + "';";
                    try {
                        pc.planconnect(query);
                        while (pc.rs.next()) {

                            wsid = pc.rs.getString(1);
//kitoroljuk a prodmatrixbol az ehez kapcsolodo teteleket
                            query = "delete from tc_prodmatrix where tc_prodmatrix.id_tc_bestations= '" + wsid + "'";
                            pc.feltolt(query, false);
//kitoroljuk a tablabol is
                            query = "delete from tc_bestations where tc_bestations.workstation = '" + ws + "';";
                            pc.feltolt(query, false);

                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

//pn       
                if (pn.length() > 0) {

                    String query = "SELECT * FROM planningdb.tc_bepns where tc_bepns.partnumber = '" + pn + "';";
                    try {
                        pc.planconnect(query);
                        while (pc.rs.next()) {

                            pnid = pc.rs.getString(1);
//kitoroljuk a prodmatrixbol az ehez kapcsolodo teteleket
                            query = "delete from tc_prodmatrix where tc_prodmatrix.id_tc_bepns = '" + pnid + "'";
                            pc.feltolt(query, false);
//kitoroljuk a tablabol is
                            query = "delete from tc_bepns where tc_bepns.partnumber = '" + pn + "'";
                            pc.feltolt(query, false);

                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

//frissitjuk a listakat-----------------------------
//pn feltoltese a jlistbe
                defaultadat1.clear();
                String query = "SELECT * FROM planningdb.tc_bepns";
                ResultSet rs = null;
                try {
                    rs = (ResultSet) pc.planconnect(query);
                } catch (SQLException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                }
                DefaultListModel lm2 = new DefaultListModel();
                lm2.clear();

                try {
                    while (rs.next()) {

                        lm2.addElement(rs.getString(2));
                        defaultadat1.add(rs.getString(2));

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                }

                jList2.setModel(lm2);

                //cella feltoltese
                defaultadat2.clear();
                query = "SELECT * FROM planningdb.tc_becells;";
                try {
                    rs = (ResultSet) pc.planconnect(query);
                } catch (SQLException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                }
                DefaultListModel lm1 = new DefaultListModel();
                lm1.clear();

                try {
                    while (rs.next()) {

                        lm1.addElement(rs.getString(2));
                        defaultadat2.add(rs.getString(2));

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                }

                jList1.setModel(lm1);

                //workstation feltoltese
                defaultadat3.clear();
                query = "SELECT * FROM planningdb.tc_bestations;";
                try {
                    rs = (ResultSet) pc.planconnect(query);
                } catch (SQLException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                }
                DefaultListModel lm3 = new DefaultListModel();
                lm3.clear();

                try {
                    while (rs.next()) {

                        lm3.addElement(rs.getString(2));
                        defaultadat3.add(rs.getString(2));

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Tc_Besetup.class.getName()).log(Level.SEVERE, null, ex);
                }

                jList4.setModel(lm3);

//prodmatrix tábla frissitese
                //tabla tesszuk a meglevo setup beallitasokat
                DefaultTableModel model = new DefaultTableModel();
                model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                query = "select  tc_prodmatrix.idtc_prodmatrix , tc_bepns.partnumber , tc_becells.cellname , tc_bestations.workstation , tc_prodmatrix.ciklusido ,tc_bepns.smt_pn from tc_prodmatrix left join tc_bepns on tc_prodmatrix.id_tc_bepns = tc_bepns.idtc_bepns  left join tc_becells on tc_becells.idtc_cells = tc_prodmatrix.id_tc_becells left join tc_bestations on tc_bestations.idtc_bestations = tc_prodmatrix.id_tc_bestations";

                pc = new planconnect();

                rs = (ResultSet) pc.planconnect(query);

                while (rs.next()) {

                    model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDouble(5), rs.getString(6)});

                }

                TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
                JLabel headerLabel = (JLabel) rendererFromHeader;
                headerLabel.setHorizontalAlignment(JLabel.CENTER);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                jTable1.setDefaultRenderer(Object.class, centerRenderer);
                jTable1.setModel(model);

//ez itt az if vége ha törlünk egyáltalán
                pc.kinyir();
                infobox info = new infobox();
                info.infoBox("Sikeres törlés!", "Törlés!");

            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable2.getModel();

        model.addRow(new Object[]{});
        jTable2.setModel(model);


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable3.getModel();
        model.addRow(new Object[]{});
        jTable3.setModel(model);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tc_Besetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tc_Besetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tc_Besetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tc_Besetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
