/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlannTool;

import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.MessageFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import org.joda.time.format.DateTimeFormat;

/**
 *
 * @author gabor_hanacsek
 */
public class Tc_Betervezo extends javax.swing.JFrame {

    /**
     */
    //nem engedjuk csukni amig megy a levelkuldes
    public static boolean level = false;
    public String[][] pns;
    public static List<String> partn = new ArrayList<String>();
    public static List<String> works = new ArrayList<String>();
    public static Map<String, Tc_Besheet> Besheets = new TreeMap();
    public static List<String[][]> ciklusidok = new ArrayList<String[][]>();
    public static ArrayList<Tc_Calcablak> calculatorablaktarolo = new ArrayList<Tc_Calcablak>();

    //betűméret
    public static String fs = "12";
    //betűtípus
    public static String fstyle = "SansSerif";
    //nezetvaltas csak egyszer fusson
    public static boolean nezetvaltas = true;
    //nezetvaltas ha 0 akkor wtf
    public static int nezet = 0;

    //műszakrend változója
    public static int comboertek;
    //a tervek időpontjainak változói
    public static String first = "";
    public static String second = "";
    public static Date one = null;
    public static Date two = null;
    public static Calendar c = Calendar.getInstance();

    //szinezes adatai
    public static int slide1 = 255;
    public static int slide2 = 255;
    public static int slide3 = 255;
    public static int slide4 = 204;
    public static int slide5 = 255;
    public static int slide6 = 255;
    public static int slide7 = 204;
    public static int slide8 = 255;
    public static int slide9 = 204;

    //oszlopallitas valtozoi
    public static int allitsuke = 2;
    public static int slider1 = 130;
    public static int slider2 = 130;
    public static List<Integer> szelessegek = new ArrayList<Integer>();

    //kalkulátor sor vagy ossz vagy oszlopig?
    public static int calc = 3;

    //ha csukodik ne fusson a kalkulator
    public static boolean csuk = false;

    //az ablak
    public static ablak a;

    public Tc_Betervezo(ablak a) throws SQLException, ClassNotFoundException {
        setExtendedState(MAXIMIZED_BOTH);

        initComponents();

        seticon();

        planconnect pc = new planconnect();

        //lekerdezzuk a ciklusidoket
        String query = "select tc_becells.cellname , tc_bepns.partnumber , tc_bestations.workstation , tc_prodmatrix.ciklusido from tc_prodmatrix \n"
                + "left join tc_becells on tc_becells.idtc_cells = tc_prodmatrix.id_tc_becells \n"
                + "left join tc_bepns on tc_bepns.idtc_bepns = tc_prodmatrix.id_tc_bepns\n"
                + "left join tc_bestations on tc_bestations.idtc_bestations = tc_prodmatrix.id_tc_bestations";
        pc = new planconnect();
        pc.planconnect(query);

        pc.rs.last();
        int utsosor = pc.rs.getRow();
        pc.rs.beforeFirst();

        String[][] ciklusidok = new String[utsosor][4];
        int i = 0;
        while (pc.rs.next()) {

            ciklusidok[i][0] = pc.rs.getString(1);
            ciklusidok[i][1] = pc.rs.getString(2);
            ciklusidok[i][2] = pc.rs.getString(3);
            ciklusidok[i][3] = pc.rs.getString(4);

            i++;
        }

        pc.kinyir();

        this.ciklusidok.add(ciklusidok);

        Tc_Cellavalaszto c = new Tc_Cellavalaszto(this);
        c.setVisible(true);
        this.a = a;
//lekerjuk a pn-eket es ws eket hogy le tudjuk ellenorizni , hogy leteznek e
        pncheck();
        wscheck();

//csinálunk egy calcablakot es beletesszuk a listaba , hogy előkapjuk amikor akarjuk
        calculatorablaktarolo.add(new Tc_Calcablak());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Tervezotabbed = new PlannTool.Tc_JTabbedPaneWithCloseIcons();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlannTool/kepek/login2.png"))); // NOI18N
        jButton8.setToolTipText("Login!");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tc_Betervező");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tervezotabbed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Tervezotabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(41, 100));

        jMenu5.setText("Felhasználó");

        jMenuItem5.setText("Bejelentkezés");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Kijelentkezés");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("UI Beállítások");

        jMenuItem1.setText("Színezési beállítások");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Betűk beállítása");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Oszlop szélesség");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu2.setText("Nézetváltás");

        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Waterfall");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem1);

        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("Sorba (PN / JOB szerint)");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem2);

        jMenu1.add(jMenu2);

        jMenu3.setText("Kalkuláció");

        buttonGroup2.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Időpontig");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem3);

        buttonGroup2.add(jRadioButtonMenuItem6);
        jRadioButtonMenuItem6.setText("Soronként");
        jRadioButtonMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem6);

        buttonGroup2.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setText("Összesen");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem5);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Riportok");

        jMenuItem4.setText("Segédlet");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem7.setText("Készlet");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Eszközök");

        jMenuItem9.setText("Setup");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem8.setText("PartNumber karbantartó");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem12.setText("Behúzós");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Data Loader");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("Nyomtatás");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Tervek kezelése");

        jMenuItem10.setText("Cellaválasztó");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem11.setText("Időintervallum beállítása");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seticon() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kepek/sanlogo.png")));

    }

    public static void pncheck() throws SQLException, ClassNotFoundException {

        //lekerdezzuk a letezo PN -eket , hogy meg tudjuk vizsgalni , hogy el fog e veszni feltoltes utan (piros)
        String query = "select tc_bepns.partnumber from tc_bepns";
        planconnect pc = new planconnect();
        pc.planconnect(query);
        partn.clear();

        while (pc.rs.next()) {

            partn.add(pc.rs.getString(1));

        }

        pc.kinyir();

    }

    public static void wscheck() throws SQLException, ClassNotFoundException {

        //lekerdezzuk a letezo PN -eket , hogy meg tudjuk vizsgalni , hogy el fog e veszni feltoltes utan (piros)
        String query = "select tc_bestations.workstation from tc_bestations";
        planconnect pc = new planconnect();
        pc.planconnect(query);
        works.clear();

        while (pc.rs.next()) {

            works.add(pc.rs.getString(1));

        }

        pc.kinyir();

    }

    //gombok engedese , letiltasa
    static void gombenged() {

//letiltjuk a gombokat ha nem planner de feltolthet tenyt
        if (!ablak.planner && ablak.muvez) {

            Tc_Betervezo.jMenuItem9.setEnabled(false);

            for (int i = 0; i < Tervezotabbed.getTabCount(); i++) {

                Besheets.get(Tervezotabbed.getTitleAt(i)).jButton11.setEnabled(true);
                Besheets.get(Tervezotabbed.getTitleAt(i)).jButton10.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).DeleteRow.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).Mernoki.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).Szinezo.setEnabled(false);
                //repainteljük a táblát a kommentek miatt
                Besheets.get(Tervezotabbed.getTitleAt(i)).jTable2.repaint();

            }
//ha planner 
        } else if (ablak.planner && !ablak.muvez) {

            Tc_Betervezo.jMenuItem9.setEnabled(true);

            for (int i = 0; i < Tervezotabbed.getTabCount(); i++) {

                Besheets.get(Tervezotabbed.getTitleAt(i)).jButton11.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).jButton10.setEnabled(true);
                Besheets.get(Tervezotabbed.getTitleAt(i)).DeleteRow.setEnabled(true);
                Besheets.get(Tervezotabbed.getTitleAt(i)).Mernoki.setEnabled(true);
                Besheets.get(Tervezotabbed.getTitleAt(i)).Szinezo.setEnabled(true);
                //repainteljük a táblát a kommentek miatt
                Besheets.get(Tervezotabbed.getTitleAt(i)).jTable2.repaint();

            }

        }
//ha se nem planner se nem tolthet fel
        if (!ablak.planner && !ablak.muvez) {

            Tc_Betervezo.jMenuItem9.setEnabled(false);

            for (int i = 0; i < Tervezotabbed.getTabCount(); i++) {

                Besheets.get(Tervezotabbed.getTitleAt(i)).jButton11.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).jButton10.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).DeleteRow.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).Mernoki.setEnabled(false);
                Besheets.get(Tervezotabbed.getTitleAt(i)).Szinezo.setEnabled(false);
                //az udv szoveget is atirjuk
                Besheets.get(Tervezotabbed.getTitleAt(i)).jLabel7.setText(ablak.user);
                //repainteljük a táblát a kommentek miatt
                Besheets.get(Tervezotabbed.getTitleAt(i)).jTable2.repaint();

            }

        }

        //a nezetvaltas radiobuttonjai
        if (Tc_Betervezo.nezet == 0) {

            Tc_Betervezo.jRadioButtonMenuItem1.setSelected(true);

        } else if (Tc_Betervezo.nezet == 1) {

            Tc_Betervezo.jRadioButtonMenuItem2.setSelected(true);

        }

    }

    static public void tablarajzolo(DefaultTableModel model, JTable table) {
        SwingUtilities.invokeLater(() -> {

            table.setModel(model);

        });
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        csuk = true;

    }//GEN-LAST:event_formWindowClosing

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        //ha van aktív besheet
        if (Tc_Betervezo.Tervezotabbed.getSelectedIndex() >= 0) {

            Tc_Szinvalasztos sz = new Tc_Szinvalasztos(Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(Tervezotabbed.getSelectedIndex())));
            sz.setVisible(true);

        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tc_Betumeret b = new Tc_Betumeret();
        b.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed

//nézetváltás
        Tc_Betervezo.nezet = 1;
//átkapcsoljuk soronkénti összeadásra
        Tc_Betervezo.calc = 1;
//a radiobuttont is atnyomjuk
        Tc_Betervezo.jRadioButtonMenuItem6.setSelected(true);

        for (int i = 0; i < Tc_Betervezo.Besheets.size(); i++) {

            Tc_AdatInterface a = new Tc_AdatInterface(Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(i)));
            a.adatbatoltnezetvaltas();
            a.tablabatolt();
            Tc_Calculator c = new Tc_Calculator(Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(i)), false, 0);
            c.run();

        }

        //beirjuk az adatbazisba a valtozast
        String query = "update tc_users set tc_users.nezet = ('1') where tc_users.username = '" + ablak.user + "'";
        planconnect pc = new planconnect();
        pc.feltolt(query, false);
        pc.kinyir();


    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // waterfall
        //visszaallitjuk a nezetvaltast
        Tc_Betervezo.nezetvaltas = true;
        Tc_Betervezo.nezet = 0;
        //gyakorlatilag lekerjuk az osszes adatot ujbol

        //eltesszuk az adatokat az ellenorzeshez , hogy valtozott e a terv
        Tc_Tervvaltozasellenor.tervellenor.clear();
        Tc_Tervvaltozasellenor t = new Tc_Tervvaltozasellenor();
        try {
            t.leker();
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Besheet.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Besheet.class.getName()).log(Level.SEVERE, null, ex);
        }

        //ciklust indítunk és végrehajtjuk a lekért cellákon a dátum beállítást
        //bepakoljuk a maptree be a sheeteket ujból
        Tc_Betervezo.Besheets.clear();
        for (int i = 0; i < Tc_Betervezo.Tervezotabbed.getTabCount(); i++) {

            String name = Tc_Betervezo.Tervezotabbed.getTitleAt(i);

            Tc_Betervezo.Besheets.put(name, (Tc_Besheet) Tc_Betervezo.Tervezotabbed.getComponentAt(i));

        }

        //meghatarozzuk a napokat , mekkora intervallumra kell beallitani a sheeteket
        SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        String first = "";
        String second = "";

        Date one = null;
        Date two = null;
        int napok = 0;
        if (!first.equals("") && !second.equals("")) {
            try {
                one = df.parse(first);
            } catch (ParseException ex) {
                Logger.getLogger(Tc_Betervezo.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                two = df.parse(second);
            } catch (ParseException ex) {
                Logger.getLogger(Tc_Betervezo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Tc_Napszamolo nap = new Tc_Napszamolo();
        if (!first.equals("") && !second.equals("")) {
            napok = nap.daysBetweenUsingJoda(one, two);
        }

        //oszlopok neve a datumbol
        Calendar c = Calendar.getInstance();
        Date dt = new Date();
        dt = c.getTime();
        org.joda.time.format.DateTimeFormatter fmt = DateTimeFormat.forPattern("yyyy-MM-dd");
        org.joda.time.format.DateTimeFormatter fmtnap = DateTimeFormat.forPattern("E");

//letrehozunk egy megfelelo jtablet
//most indítjuk a nagy ciklust amiben végigpörgetjük a sheeteket
//beallitjuk a kalkulaciot idopontig
        Tc_Betervezo.calc = 3;
        Tc_Betervezo.jRadioButtonMenuItem3.setSelected(true);

        for (int b = 0; b < Tc_Betervezo.Tervezotabbed.getTabCount(); b++) {

            Tc_Leker leker = new Tc_Leker(Tc_Betervezo.Tervezotabbed.getTitleAt(b), "groupleker");

        }

//beirjuk az adatbazisba a valtozast
        String query = "update tc_users set tc_users.nezet = ('0') where tc_users.username = '" + ablak.user + "'";
        planconnect pc = new planconnect();
        pc.feltolt(query, false);
        pc.kinyir();


    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed

        Tc_Betervezo.calc = 3;


    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem6ActionPerformed
        // TODO add your handling code here:

        Tc_Betervezo.calc = 1;

    }//GEN-LAST:event_jRadioButtonMenuItem6ActionPerformed

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        // TODO add your handling code here:

        Tc_Betervezo.calc = 2;

    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // oszlop szélesség
        Tc_Oszlopallito o = new Tc_Oszlopallito(Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(Tc_Betervezo.Tervezotabbed.getSelectedIndex())));
        o.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // segedlet
        Tc_Segedletablak s = new Tc_Segedletablak();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // bejelentkezés
        Tc_Bejelentkezes b = new Tc_Bejelentkezes(a);
        b.nyit = false;
        b.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        //kijelentkezés
        //a nem vagyok planner gomb
        ablak.planner = false;
        ablak.muvez = false;
        ablak.user = "Ismeretlen";
        Tc_Betervezo.gombenged();

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // készlet
        Tc_Keszletfromterv k = new Tc_Keszletfromterv();
        k.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // pn karbantartó
        Tc_Pnkarbantarto p = new Tc_Pnkarbantarto("");
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // setup
        Tc_Besetup c = null;
        try {
            c = new Tc_Besetup();
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Betervezo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Betervezo.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setVisible(true);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // cellaválasztó
        try {
            Tc_Cellavalaszto c = new Tc_Cellavalaszto(this);
            c.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Tc_Betervezo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tc_Betervezo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // idő ablak
        Tc_Idointervallum i = new Tc_Idointervallum();
        i.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        //behúzós
        Tc_Behuzos bh = new Tc_Behuzos();
        bh.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // dataloader
        Tc_DataLoader d = new Tc_DataLoader(Tc_Betervezo.Besheets.get(Tc_Betervezo.Tervezotabbed.getTitleAt(Tc_Betervezo.Tervezotabbed.getSelectedIndex())));
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        //nyomtatás
        MessageFormat header = new MessageFormat("Report print");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {

            PrintRequestAttributeSet attr = new HashPrintRequestAttributeSet();

            Besheets.get(Tervezotabbed.getTitleAt(Tervezotabbed.getSelectedIndex())).jTable2.print(JTable.PrintMode.FIT_WIDTH, header, footer);

            // jTable2.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {

            System.err.format("Cannot print", e.getMessage());

        }// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tc_Betervezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tc_Betervezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tc_Betervezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tc_Betervezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane Tervezotabbed;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    public static javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    // End of variables declaration//GEN-END:variables
}
