/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlannTool.KAPACITAS;

import PlannTool.CONNECTS.*;
import PlannTool.ablak;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author gabor_hanacsek
 */
public class Kapacitas_StationChooser extends javax.swing.JFrame {

    /**
     * Creates new form Kapacitas_StationChooser
     */
    public Kapacitas_StationChooser() throws SQLException, ClassNotFoundException {
        initComponents();
        GatherStations();
    }

    //összeszedjük az összes állomást amire lehetséges a kapacitás elemzés
    public void GatherStations() throws SQLException, ClassNotFoundException {

        DefaultListModel allomaslista = new DefaultListModel();

        ArrayList<String> Stations = new ArrayList<>();
        //lekérdezzük először az SMT-st

        String query = "select distinct stations.name from stations\n"
                + "left join terv on terv.stationid = stations.id\n"
                + "where terv.active = 1";

        planconnect pc = new planconnect();
        pc.lekerdez(query);

        while (pc.rs.next()) {

            allomaslista.addElement(pc.rs.getString(1));

        }

        //lekerdezzük a backendet is
        query = "select distinct tc_becells.cellname from tc_becells\n"
                + "left join tc_terv on tc_terv.idtc_becells = tc_becells.idtc_cells\n"
                + "where active = 2";

        pc.lekerdez(query);
        while (pc.rs.next()) {

            allomaslista.addElement(pc.rs.getString(1));

        }

        jList1.setModel(allomaslista);

        pc.kinyir();

    }

    public void LoadStations() {
//itt példányosítani kell a kiválasztott állomásokat és betenni a tabbed painre és egy gyüjtőbe

//végigmegyünk a listán és ha selected létrehozunk egy példányt azzal a névvel és beletesszük a threemap ba is
        List<String> allomasok = new ArrayList<String>();
        allomasok = jList1.getSelectedValuesList();
//ha nem valasztottunk ki allomast

        if (allomasok.size() == 0) {

            JOptionPane.showMessageDialog(this,
                    "Nem választottál ki egyetlen állomást sem",
                    "Hiba!",
                    JOptionPane.ERROR_MESSAGE);
            return;

        }
        //ha van vvalami kiválasztva     
        for (int i = 0; i < allomasok.size(); i++) {

            Kapacitas_Station k = new Kapacitas_Station();
            //hozzáadjuk a tabbedpainhez
            Kapacitas.jTabbedPane1.addTab(allomasok.get(i).toString(), k);
            //betesszuk a threemap be
            Kapacitas.allomasok.put(allomasok.get(i).toString(), k);

        }

        this.dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Állomás választó!");

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // állomás betöltő
        LoadStations();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kapacitas_StationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kapacitas_StationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kapacitas_StationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kapacitas_StationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Kapacitas_StationChooser().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
